Add 141 photo
markpolyak/faces-dataset pull request #35
Opened 2024-01-13 16:04 UTC by NikoBorodin

2024-01-16 07:03 UTC, KleinerKaktus455 requested changes
Не сталf оставлять одинаковые комментарии ко всем фото. Ошибка везде одна: фото НЕ обрезаны. См файлик с требованиями. То, что есть сейчас, не годится

2024-01-16 07:03 UTC, KleinerKaktus455 commented on symphony_personal4/-2TQpRQQdgc.jpg
Фото необходимо обрезать. См файл с требованиями

2024-01-16 07:04 UTC, KleinerKaktus455 commented on symphony_personal4/-2TQpRQQdgc.jpg
PR, к слову, так оформлять нельзя. Описание пустое. К заданию это замечание отношения не имеет

2024-01-16 07:06 UTC, KleinerKaktus455 commented on symphony_personal4/-2TQpRQQdgc.jpg
Фото 28 плохого качества. После обрезки ситуация будет более печальная. Фото необходимо удалить или заменить

2024-01-16 12:16 UTC, NikoBorodin reviewed
Здравствуйте, прошу прощения что не написал дополнительно тут комментарий - думал что коммита в баше будет достаточно. Я полностью исправил работу, большую часть фото обрезал, часть заменил.

2024-01-16 21:25 UTC, NikoBorodin reviewed
Здравствуйте, я обрезал еще несколько фотографий

2024-01-18 16:26 UTC, KleinerKaktus455 approved these changes
Все в порядке, задание принимаю

2024-01-18 16:26 UTC, merged

2024-01-18 16:30 UTC, markpolyak commented
@NikoBorodin Не могу поставить оценку из-за отсутствия отчета в ЛК